### ISSUE TITLE
Consider alternate syntax for inclusive/exclusive ranges

### ISSUE THREAD

**Issue by joshtriplett** [theryangeary/choose#11]
It would be nice to have an inline syntax for explicitly inclusive and explicitly exclusive ranges, not just a separate `-x` option that changes the behavior of `:`. That way, it'd be possible to specify both inclusive and exclusive ranges on the same command line, and to not have to go back and change options when typing ranges.

For example, using Rust's syntax:

Syntax | Meaning
------ | -------
`2..5` | 2 to 5, not including 5
`2..=5` | 2 to 5, including 5
`2:5` | 2 to 5; including 5 by default, excluding 5 if `-x` passed

(A different syntax would be fine, as long as it's self-explanatory.)

**Comment by theryangeary** [comment]
I do like Rust's way of specifying in/ex-clusivity and I think this is a pretty good idea and shouldn't be too hard to implement either. I went with the `:` originally because it felt Pythonic and I think Python is just a widely used, widely familiar syntax. I may add this because it really has some utility but will likely also keep the `:` syntax for people that prefer it.

**Comment by theryangeary** [comment]
This syntax has been added. Thanks for the recommendation.

**Comment by joshtriplett** [comment]
Thank you!
