### ISSUE TITLE
Steal ideas from fex

### ISSUE THREAD

**Issue by The-King-of-Toasters** [theryangeary/choose#5]
This project is quite similar to one I came across a couple months ago: [fex (field extraction)](https://www.semicomplete.com/projects/fex/). It has a different syntax for selecting fields, and only supports single character delimiters, but it also has some nice features:

## Non-greedy String Splitting

Given the input `a:b::c:::d`, a standard selection of fields `0:2` would print `a:b:c`, whilst a non-greedy selection would print `a:b:`. This would probably be hard to implement due to regex delimiters.

## Multi-Pass selections

Field selections could have multiple stages, so that each split string could be split with another delimiter and another field selected within. There's a great example on the project for splitting web-server access logs like so.

```
194.25.90.180 - - [19/Jan/2015:12:58:19 +0000] "GET /run?command=ls HTTP/1.1" 200 115 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36"
``` 

Piping this to `fex 1 '"2 2'`, split the line by spaces and select field 1, then split the line by double-quotes, select field 2, split that by spaces, and select field 2 from the result. This gives:

`194.25.90.180 /run?command=ls`

## Select fields that match regex

Any field that matches the regular expression `/regexp/` would be selected.

**Comment by theryangeary** [comment]
Hi @The-King-of-Toasters! Thanks for pointing out `fex` - I hadn't run across that before. You bring up some interesting points.
## Non-greedy String Splitting
I agree, this should be a feature. It actually wouldn't be terribly difficult to implement, because for performance purposes right now `choose` searches for a non-repeating delimiter regex and then filters out empty fields. To add this, all we would need is to remove the filter based on a flag.
## Multi-Pass selections
This is definitely an interesting proposition I hadn't considered, and a nice feature that `fex` offers. It would definitely take a breaking change to the API, since choices are assumed to all be based off 1 field separator regex at the moment. For the example you gave above, `choose 0 6` accomplishes the same output, so I'm not sure it would be worth overhauling the API for it. If you have other examples of scenarios that can't be accomplished with the way things work now, I'd be interested to hear them!
## Select fields that match regex
I believe the functionality you're describing here is `grep -o`. So if the field you were concerned with were the IP address in the example above: `grep -o -E "([0-9]{1,3}\.){3}[0-9]{1,3}"`. In keeping with the UNIX philosophy, `choose` will do one thing and do it well, and leave that functionality up to `grep`.

**Comment by theryangeary** [comment]
@The-King-of-Toasters do you have any ideas regarding Multi-Pass selections of things that can't be accomplished with the current API?
